# Project information
site_name: mlflow-introduction
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Section 01 Intorduction to MLflow: Section_001_MLflow_Introduction.md
  - Section 02 MLflow Tracking: Section_002_MLflow_Tracking.md

site_author: Sunny Bhaveen Chandra
site_description: >-
  This contains introduction to mlflow library

# Repository
repo_name: c17hawke/mlflow-introduction
repo_url: https://github.com/c17hawke/mlflow-introduction

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/c17hawke
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/c17hawke"  target="_blank" rel="noopener">Sunny Bhaveen Chandra</a>
